[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm run start"
  port = 3000
  targetPort = 3000 