[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  port = 9000
  targetPort = 9000 